version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_bank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./backend
    container_name: node_bank
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=mysql://root:root@db:3306/bank
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  db_data:
